swagger: '2.0'
info:
  title: sample
  description: sample
  version: 1.0.0
host: sample-l6wc7ausiq-ew.a.run.app
schemes:
  - https
produces:
  - application/json
x-google-backend:
  address: https://sample-l6wc7ausiq-ew.a.run.app
  protocol: h2
paths:
  /hello:
    get:
      summary: Greet a user
      operationId: hello
      responses:
        '200':
          description: A successful response
          schema:
            type: string

security:
  - ServiceAccount: []

securityDefinitions:
  ServiceAccount:
    authorizationUrl: ""
    flow: "implicit"
    type: "oauth2"
    x-google-issuer: "sample-sa@db-dns-01.iam.gserviceaccount.com"
    x-google-jwks_uri: "https://www.googleapis.com/robot/v1/metadata/x509/sample-sa@db-dns-01.iam.gserviceaccount.com"